In [6]:
import numpy as np

In [108]:
#Задание 1
#Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

#?подскажите, можно ли как-то выполнить сортировку с помощью функций, чтобы получить numpy array?
#пробовала, sorted(np.arange(10), reverse = True) но в итоге получаю type = list
N = 10
rez = np.arange(N)[::-1]
print(rez)

[9 8 7 6 5 4 3 2 1 0]


In [94]:
#Задание 2
#Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
N = 5
matrix = np.diag(np.arange(N)[::-1])
main_diag_sum = sum(np.diag(matrix))
print(matrix)
print(main_diag_sum)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
10


In [96]:
#Решите систему уравнений:
#4x + 2y + z = 4
#x + 3y = 12
#5y + 4z = -3

from numpy import linalg

In [110]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [100]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True